baseurl = "https://muchlis.dev"
title = "Muchlis Portfolio"
theme = "hugo-creative-portfolio-theme"
languageCode = "id-ID"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Situs Portofolio Muchlis"
  copyright = "&copy;2021 Muchlis"
  sidebarAbout = [
    "Selamat datang, saya Muchlis, Seorang Software Engineer yang berfokus pada dua bidang, yaitu Backend dan Mobile Apps.",
    "Banjarmasin-Indonesia."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "whois.muchlis@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portofolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"

  [[params.navlinks]]
  name = "Tentang Saya"
  url = "about/"

  [[params.navlinks]]
  name = "Kontak"
  url = "contact/"

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "whois.muchlis@gmail.com"
  twitter       = ""
  linkedin      = "https://www.linkedin.com/in/muchlis-mrts/"
  stackoverflow = ""
  instagram     = "https://www.instagram.com/ig_muchlis/"
  github        = "https://github.com/muchlist"
  youtube       = ""
  whatsapp      = "https://wa.me/6281231847434?text=Saya%20melihat%20portofolio%20kamu%20di%20muchlis_netlify_app"

